
### Create a new Customer
POST http://localhost:4004/api/data/customers/Customers
Content-Type: application/json
Authorization: Basic manager:123

{
  "ID": "1",
  "name": "Domestic Customer AU 1",
  "contact": "7980511342"
}

### Get All Customers

GET http://localhost:4004/api/data/customers/Customers
Content-Type: application/json
Authorization: Basic manager:123



